image: gcc:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - apt-get update --yes
  - apt-get install --yes cmake

stages:
  - build
  - test

build:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ..
    - cmake --build .
  artifacts:
    paths:
      - build/

test:
  stage: test
  script:
    - ./build/bptree_test
  dependencies:
    - build
  artifacts:
    paths:
      - build/

bench:
  stage: benchmark
  script:
    - ./build/bptree_benchmark --benchmark_out_format=json --benchmark_out=bench.json
  dependencies:
    - build
  artifacts:
    paths:
      - build/