name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: cmake
      run: cmake --debug-output .
    - name: cmake build
      run: cmake build .
    - name: tests
      run: ./bptree_test
